# Core code algorithm generated by AI, post solving manually, via prompt below using CoPilot ( https://copilot.microsoft.com/ ):

"""
Write a Python function max_digits_subsequence(num, k) that constructs the largest possible number from the digits of num.

Requirements:

* num is an integer input.
* k is the number of digits to use in the output.

The function must select digits in their original order of appearance (no reordering after selection).

Digits can be consecutive or non‑consecutive, but each index in the input number can only be used once.

The algorithm should always return exactly k digits if possible.

Examples:

max_digit_subsequence(818181911112111, 2)  # Expected output: 92
max_digit_subsequence(818181911112111, 3)  # Expected output: 921
max_digit_subsequence(811111111111119, 2)  # Expected output: 89
max_digit_subsequence(987654321, 3)        # Expected output: 987
max_digit_subsequence(123456789, 2)        # Expected output: 89
"""

def max_digits_subsequence(num: int, k: int) -> int:
    """
    Returns the largest possible number formed from k digits
    (consecutive or non-consecutive) in the input number, preserving order.
    """
    digits = [int(d) for d in str(num)]
    chosen = []
    start = 0

    for remaining in range(k, 0, -1):
        # Look ahead enough to leave room for remaining digits
        end = len(digits) - remaining + 1
        # Pick the largest digit in the allowed window
        max_digit = max(digits[start:end])
        max_index = digits.index(max_digit, start, end)
        chosen.append(max_digit)
        # Move start beyond the chosen index
        start = max_index + 1

    return int("".join(map(str, chosen)))


# Use the AI (CoPilot) generated method above to solve parts 1 & 2

def solve_part1(filename):
    return process_input_data_lines(filename, 2)


def solve_part2(filename):
    return process_input_data_lines(filename, 12)


def process_input_data_lines(filename:str, digits:int=2) -> int:
    ans = 0

    # Iterate over each line in the file
    with open(filename, "r") as f:
        for line in f:
            line = line.strip()  # remove leading/trailing whitespace
            if line:             # check if not empty
                ans += max_digits_subsequence(line, digits)
    return ans
