---
config:
  logLevel: 'debug'
  theme: 'forest'
---
%% Ref.: https://mermaid.js.org/syntax/timeline.html
timeline
title Advent of Code 2025 - Puzzle Days (in December) 
1 <br>Secret Entrance: Modular arithmetic
2 <br>Gift Shop: Repeating number / string sub-sequences
3 <br>Lobby: Max digits in number
4 <br>Printing Departments: 2D grid symbol matching & neighbour counting
5 <br>Cafeteria: Positive integer number ranges / intervals
6 <br>Trash Compactor: Column based parsing of data input
7 <br>Laboratories: Paths through 2D grid
8 <br>Playground: Ordering (by Euclidian distance) & grouping 3D point pairs.
9 <br>Movie Theater: 2D points, rectangles sizes & ray-casting
10 <br>Factory: Minimal solutions to sets of linear equations
11 <br>Reactor: Graph paths + caching
12 <br>Christmas Tree Farm: Shape fitting in 2D grids

%% Version 2025-12-17a